# run SV calling (0) or vanilla jobs (1)
echo_run: 0

# select one or more callers
enable_callers:
  - manta
  - delly
  - lumpy
  - gridss

# (s)ingle-sample or (p)aired-samples analysis
mode: p

# filepath of the reference genome in FASTA format
genome: /root/workflow/data/fasta/chr22.fasta

# filepath of the exclusion list in BED format
exclusion_list: /root/workflow/data/ENCFF001TDO.bed
exclude_regions: 1 # use the list (1) or don't (0)

# file extensions used by the workflow
file_exts:
  fasta: .fasta
  fasta_idx:
    - .fasta.fai  # faidx index file
    - .fasta.bwt  # BWA v0.6.x index files
    - .fasta.amb  # |
    - .fasta.ann  # |
    - .fasta.pac  # |
    - .fasta.sa   # |
  bam: .bam
  bam_idx: .bam.bai
  vcf: .vcf
  bcf: .bcf
  bed: .bed

# CSV file with (paired) WGS samples for analysis
# format: PATH,SAMPLE1,SAMPLE2
#   paired SAMPLE1(tumor)/SAMPLE2(normal) files used for somatic analysis while
#   single SAMPLE1 file used for germline or tumor-only analysis (Manta only)
samples: /root/workflow/samples.csv

# settings or requirements per SV caller
callers:
  manta:
    threads: 24         # number of threads used
    memory: 16384       # allocated memory (MB)
    tmpspace: 0         # min. temporary disk space (MB); not in use by Manta
    outdir: manta_out   # output dir relative to PATH/SAMPLE/... (see above)
    tumor_only: 0       # germline (0) or tumor-only analysis (1)

  delly:
    threads: 2  # max. 2 for paired-samples otherwise defaults to 1
    memory: 8192
    tmpspace: 0  # not in use
    outdir: delly_out
    sv_types:
        - BND  # translocation
        - DEL  # deletion
        - DUP  # duplication
        - INS  # insertion
        - INV  # inversion

  lumpy:
    threads: 1  # multi-threading not supported
    memory: 32768
    tmpspace: 0  # e.g., 10240
    outdir: lumpy_out

  gridss:
    threads: 24
    memory: 63488
    tmpspace: 0  # e.g., 102400
    outdir: gridss_out

postproc:
  survivor:
    threads: 1
    memory: 1024
    tmpspace: 0  # not in use
    outdir: survivor
    filter:         # filter SVs using a BED file (see 'exclusion_list')
      min_size: -1  # min. SV size (-1 to disable)
      max_size: -1  # max. SV size (-1 to disable)
      min_freq: 0   # min. allele frequency (0 or 1)
      min_sup: -1   # min. number of reads support: RE flag (-1 to disable)

    merge:             # merge callers' output into one (union) SV set
      infile: all.txt  # list of VCF files
      max_dist: 100    # max. distance (bp) between breakpoints
      min_sup: 1       # min. number of supporting callers
      use_type: 0      # take SV type into account (1=yes or 0=no)
      use_strand: 0    # take the strands of SVs into account (1=yes or 0=no)
      use_size: 0      # estimate distance based on SV size (1=yes or 0=no)
      min_size: 0      # min. SV size (bp)
      outfile: all.vcf
